name: UKnetUtilities
version: 1.4
main: me.elgamer.UKnetUtilities.Main
description: UKnet Utilities Plugin

commands:
    ll:
        aliases: [location, coordinates, co]
        usage: /<command>
        description: Get coordinates of player.
    nv:
        aliases: [nightvision]
        usage: /<command>
        description: Give the player night vision.